qeglplatformscreen.cpp: reorder headers to fix build with egl enabled
fixes:
In file included from /home/superandy/tmp/oe-core-glibc/sysroots/varsomimx6q/usr/include/X11/Xlib.h:44:0,
                 from /home/superandy/tmp/oe-core-glibc/sysroots/varsomimx6q/usr/include/EGL/eglvivante.h:244,
                 from /home/superandy/tmp/oe-core-glibc/sysroots/varsomimx6q/usr/include/EGL/eglplatform.h:38,
                 from /home/superandy/tmp/oe-core-glibc/sysroots/varsomimx6q/usr/include/EGL/egl.h:39,
                 from /home/superandy/tmp/oe-core-glibc/work/cortexa9t2hf-vfp-neon-mx6qdl-angstrom-linux-gnueabi/qtbase/5.5.0+gitAUTOINC+2fde9f59ee-r0/git/src/platformsupport/eglconvenience/qeglplatformscreen_p.h:52,
                 from /home/superandy/tmp/oe-core-glibc/work/cortexa9t2hf-vfp-neon-mx6qdl-angstrom-linux-gnueabi/qtbase/5.5.0+gitAUTOINC+2fde9f59ee-r0/git/src/platformsupport/eglconvenience/qeglplatformscreen.cpp:34:
../../include/QtCore/../../../git/src/corelib/io/qurl.h:131:9: error: expected identifier before numeric constant
         None = 0x0,
         ^

This patch has a very limited lifetime: In branch dev and 5.6 the patched file is gone. Therefore:

Upstream-Status: Pending

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>