Revert "Fix workaround in pthread destructor"
This reverts commit 81ce2d1d6fa741de4d27b939a378147a02019ec1.

currentThreadData was reverted in 5.12 before this commit:

81ce2d1d6f Fix workaround in pthread destructor
8867e0eaa7 Revert "Remove pthread storage for thread local data"
78665d8a0c Remove pthread storage for thread local data

causing build failures in configurations which use this
| /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/qtbase/5.15.2+gitAUTOINC+40143c189b-r0/git/src/corelib/thread/qthread_unix.cpp: In function 'void destroy_current_thread_data(void*)':
| /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-halium-webos-linux-gnueabi/qtbase/5.15.2+gitAUTOINC+40143c189b-r0/git/src/corelib/thread/qthread_unix.cpp:121:5: error: 'currentThreadData' was not declared in this scope
|   121 |     currentThreadData = data;
|       |     ^~~~~~~~~~~~~~~~~