evdevkeyboard: fix input_event time related compile
Fixes:

  evdevkeyboard/qevdevkeyboardhandler.cpp: In member function ‘void QEvdevKeyboardHandler::switchLed(int, bool)’:
  evdevkeyboard/qevdevkeyboardhandler.cpp:153:28: error: ‘struct input_event’ has no member named ‘time’; did you mean ‘type’?
       ::gettimeofday(&led_ie.time, 0);
                              ^~~~
                              type

Task-number: QTBUG-84012
Change-Id: I1d127561e0406ae570da656d3e31f9434c7b8798
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>
(cherry picked from commit c5b8b662105cc5ced968da9f567fe1134c52d6b5)

Upstream-Status: Backport [5.15 d9b430560a6ea28fc6024cede34d765c7bd68e22]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>